CARDS = {
  'title': 'English/Spanish',
  'left-category': 'Spanish',
  'right-category': 'English',
  'cards': [
    { 'left': 'compartir', 'right': 'share' },
    { 'left': 'así', 'right': 'so' },
    { 'left': 'así están las cosas', 'right': 'that’s the way things are' },
    { 'left': 'hasta', 'right': 'until' },
    { 'left': 'cojín', 'right': 'cushion' },
    { 'left': 'llorar', 'right': 'cry' },
    { 'left': 'correo', 'right': 'mail' },
    { 'left': 'Venga/vengo', 'right': 'come' },
    { 'left': 'a que sí', 'right': 'isn’t that right?' },
    { 'left': 'Soltar', 'right': 'drop' },
    { 'left': 'a ver', 'right': 'let’s see' },
    { 'left': 'factura', 'right': 'bill' },
    { 'left': 'qué bien ', 'right': 'great' },
    { 'left': 'verdura', 'right': 'vegetable' },
    { 'left': 'vegetal', 'right': 'plant' },
    { 'left': 'bastante', 'right': 'enough' },
    { 'left': 'acordarse', 'right': 'remember' },
    { 'left': 'hace…', 'right': '…ago' },
    { 'left': 'corresponsales', 'right': 'correspondants' },
    { 'left': 'contar', 'right': 'count' },
    { 'left': 'no… sino…', 'right': 'not… but…' },
    { 'left': 'suerte', 'right': 'luck' },
    { 'left': 'nadie', 'right': 'no one' },
    { 'left': 'alguien', 'right': 'someone' },
    { 'left': 'cualquiera', 'right': 'anyone' },
    { 'left': 'cualquier', 'right': 'any', 'notes': 'always goes before noun' },
    { 'left': 'al menos', 'right': 'at least' },
    { 'left': 'enseñar', 'right': 'teach' },
    { 'left': 'almohada', 'right': 'pillow' },
    { 'left': 'por su puesto', 'right': 'of course' },
    { 'left': 'cómodo', 'right': 'comfortable' },
    { 'left': 'simpático/agradable', 'right': 'nice' },
    { 'left': 'amable', 'right': 'friendly' },
    { 'left': 'enfrente', 'right': 'in front' },
    { 'left': 'regalar', 'right': 'to present/give a gift' },
    { 'left': 'de verdad', 'right': 'really/sure' },
    { 'left': 'vale', 'right': 'okay' },
    { 'left': 'horno', 'right': 'oven' },
    { 'left': 'estufa', 'right': 'stove' },
    { 'left': 'piernas', 'right': 'legs' },
    { 'left': 'pedalear', 'right': 'pedal' },
    { 'left': 'te queda bien  ', 'right': 'it suits you well' },
    { 'left': 'qué tal', 'right': 'what’s up' },
    { 'left': 'ducha', 'right': 'shower' },
    { 'left': 'broma', 'right': 'joke' },
    { 'left': 'ni hablar', 'right': 'no way' },
    { 'left': 'libre', 'right': 'free' },
    { 'left': 'ahí', 'right': 'there (close)' },
    { 'left': 'allí', 'right': 'there (far)' },
    { 'left': 'arreglar', 'right': 'fix' },
    { 'left': 'criado', 'right': 'servant' },
    { 'left': 'podriá', 'right': 'might/could' },
    { 'left': 'cállate', 'right': 'shut up' },
    { 'left': 'celebrar', 'right': 'celebrate' },
    { 'left': 'ponerse', 'right': 'put on' },
    { 'left': 'revista', 'right': 'magazine' },
    { 'left': 'ni', 'right': 'neither' },
    { 'left': 'subir', 'right': 'go up' },
    { 'left': 'esconder', 'right': 'hide' },
    { 'left': 'dueña', 'right': 'owner' }

  ]
}